apiVersion: v1
kind: Service

metadata:
  namespace: "{{ .Values.namespace }}"
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
    owner: "{{ .Values.owner }}"

spec:
  ports:
  -
    name: "{{ .Values.name }}"
    port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: 8080
  {{ if .Values.developmentMode }}
  -
    name: "{{ .Values.name }}-go-delve"
    port: {{ .Values.goDelvePort }}
    protocol: TCP
    targetPort: 4000
  {{ end }}

  selector:
    app: {{ .Values.name }}

  type: LoadBalancer
