name: Tests

on: [pull_request]

jobs:

  gotest:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
    - 
      name: Setup go
      uses: actions/setup-go@v2
    - 
      name: Download Go modules
      run: go mod download
    - 
      name: Run Go Tests
      run: go test -v $(go list ./... | grep -v /vendor/)

  helmtest:
    name: E2E Testing
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
    -
      name: Set up Helm
      uses: azure/setup-helm@v1
    -
      uses: actions/setup-python@v2
    -
      name: Set up chart-testing
      uses: helm/chart-testing-action@v2.0.1
    -
      name: Run chart-testing (lint)
      run: ct lint --all --chart-dirs kubernetes/helm/
    -
      name: Create kind cluster
      uses: helm/kind-action@v1.1.0
    -
      name: Run chart-testing (install)
      run: ct install --all --chart-dirs kubernetes/helm/
